apiVersion: v2
name: parent-chart
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "0.1.0"
icon: https://www.google.com/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png
dependencies:
- name: child1
  version: "0.1.0"
  repository: "file://../child1"
  condition: child1.enabled
- name: child2
  version: "0.1.0"
  repository: "file://../child2"
  condition: child2.enabled